alias cd..='cd ..'
alias la='ls -la --color=auto'
alias pulldrop='cp -u ~/Dropbox/config ~/.[^.]*'
alias pushdrop='cp -u ~/.[^.]* ~/Dropbox/config'
alias sapt='sudo apt-get'
alias ssh8='ssh scucca@files.8bit.is'
alias sshdb='ssh scucca@davebuntu'
alias sshgq='ssh ubuntu@46.149.24.44'
alias saptupup='sudo apt-get update && sudo apt-get -y upgrade'
